%% Add Directory Tree to MATLAB Path

addpath(genpath('~/Repositories/WOGRSS'));
cd ~/Repositories/WOGRSS

%% Generate Input Parameter Object

run ./prm/californiaSample.m

%% Select Study Site

[hucID, hucIndex] = getHucCodeFnc( ...
    p.hucCodeShapeStruct, ...
    p.overlayShapeStruct);

%% Generate Grid Mask

[gridMask, gridMaskGeoRasterRef] = hucCode2GridMaskFnc( ...
    p.hucCodeShapeStruct, ...
    hucIndex, ...
    p.gridDensity);

%% Extract Source Index

sourceIndex = getSourceIndexFnc( ...
    gridMaskGeoRasterRef, ...
    gridMask);

%% Generate Raster Mosaic List

rasterMosaicList = getRasterMosaicListFnc( ...
    p.inputRasterDirectory, ...
    gridMaskGeoRasterRef );

%% View Mosaic Extent

plotHandle = rasterMosaicExtentPlot( ...
    p.overlayShapeStruct, ...
    rasterMosaicList, ...
    gridMaskGeoRasterRef );

%% Generate Raster Mosaic Dataset

rasterMosaicData = rasterMosaicList2DataFnc( ...
    rasterMosaicList, ...
    p.rasterNanFloor, ...
    gridMaskGeoRasterRef );

%% View Raster Mosaic Dataset

rasterBasinOutlinePlot( ...
    rasterMosaicData, ...
    gridMaskGeoRasterRef, ...
    p.hucCodeShapeStruct, ...
    hucIndex );

%% Generate Vector Dataset

vectorMosaicData = vectorIntersectDataFnc( ...
    p.overlayShapeStruct, ...
    p.hucCodeShapeStruct, ...
    hucIndex, ...
    gridMaskGeoRasterRef );

%% View Vector Mosaic Dataset

geoshow(vectorMosaicData);
