function [ rawRasterMosaicData ] = extractRawRasterMosaicDataFnc( ...
                                                    topLevelRasterDir, ...
                                                    topLevelVectorDir, ...
                                                    rasterNanFloors, ...
                                                    gridDensity, ...
                                                    attributeFieldCell,...
                                                    hucCodeShapeStruct, ...
                                                    hucIndex, ...
                                                    gridMask, ...
                                                    gridMaskGeoRasterRef )
%% Parse Inputs

P = inputParser;

addRequired(P,'nargin',@(x) ...
    x == 9);
addRequired(P,'nargout',@(x) ...
    x == 1);
addRequired(P,'topLevelRasterDir',@(x) ...
    isdir(x) && ...
    ischar(x) && ...
    ~isempty(x));
addRequired(P,'topLevelVectorDir',@(x) ...
    isdir(x) && ...
    ischar(x) && ...
    ~isempty(x));
addRequired(P,'rasterNanFloors',@(x) ...
    isnumeric(x) && ...
    ~isempty(x));
addRequired(P,'gridDensity',@(x) ...
    isscalar(x) && ...
    ~isempty(x));
addRequired(P,'hucCodeShapeStruct',@(x) ...
    isstruct(x) && ...
    ~isempty(x));
addRequired(P,'hucIndex',@(x) ...
    isscalar(x) && ...
    ~isempty(x));
addRequired(P,'gridMask',@(x) ...
    isnumeric(x) && ...
    ismatrix(x) && ...
    ~isempty(x));
addRequired(P,'gridMaskGeoRasterRef',@(x) ...
    isa(x,'spatialref.GeoRasterReference'));

parse(P,nargin,nargout,topLevelRasterDir,topLevelVectorDir, ...
    rasterNanFloors,gridDensity,hucCodeShapeStruct,hucIndex,gridMask, ...
    gridMaskGeoRasterRef);

%% Extract Raster Mosaic Data

disp('**Extracting Raster Datasets**');

rasterMosaicData = extractRasterMosaicDataFnc( ...
    topLevelRasterDir, ...
    rasterNanFloors, ...
    gridMask, ...
    gridMaskGeoRasterRef );

%% Generate Derived Data Products

disp('**Generating Derived Raster Datasets**')

rasterNames = rasterMosaicData(:,2);
demMatch = strcmp(rasterNames,'dem');

if any(demMatch) == 0
    
    warning('No DEM Found & No DEM Derived Raster Datasets Generated');
    
else 
    
    demRasterData = rasterMosaicData{demMatch,1};
    gradientMosaicData = dem2GradientMosaicDataFnc( ...
    demRasterData, ...
    gridDensity, ...
    gridMask, ...
    gridMaskGeoRasterRef );

end

%% Extract Vector Mosaic Data

disp('**Extracting Vector Datasets**');

vectorMosaicData = extractVectorMosaicDataFnc( ...
    topLevelVectorDir, ...
    hucCodeShapeStruct, ...
    hucIndex, ...
    gridMaskGeoRasterRef );

%% Rasterize Vector Mosaic Data

disp('**Rasterizing Vector Datasets**');

vector2RasterMosaicData = vector2RasterMosaicDataFnc( ...
    vectorMosaicData, ...
    attributeFieldCell, ...
    gridMask, ...
    gridMaskGeoRasterRef );

%% Concatenate to Final Output

disp('**Assembling Final Output**');

rawRasterMosaicData = vertcat( ...
    rasterMosaicData, ...
    vector2RasterMosaicData, ...
    gradientMosaicData);

end