function [ rawRasterMosaicData ] = extractRawRasterMosaicDataFnc( ...
                                                    topLevelRasterDir, ...
                                                    topLevelVectorDir, ...
                                                    rasterNanFloors, ...
                                                    gridDensity, ...
                                                    attributeFieldCell,...
                                                    hucCodeShapeStruct, ...
                                                    hucIndex, ...
                                                    gridMask, ...
                                                    gridMaskGeoRasterRef )
%% Parse Inputs

P = inputParser;

addRequired(P,'nargin',@(x) ...
    x == 9);
addRequired(P,'nargout',@(x) ...
    x == 1);
addRequired(P,'topLevelRasterDir',@(x) ...
    isdir(x) && ...
    ischar(x) && ...
    ~isempty(x));
addRequired(P,'topLevelVectorDir',@(x) ...
    isdir(x) && ...
    ischar(x) && ...
    ~isempty(x));
addRequired(P,'rasterNanFloors',@(x) ...
    isnumeric(x) && ...
    ~isempty(x));
addRequired(P,'gridDensity',@(x) ...
    isscalar(x) && ...
    ~isempty(x));
addRequired(P,'attributeFieldCell',@(x) ...
    iscell(x) && ...
    ~isempty(x));
addRequired(P,'hucCodeShapeStruct',@(x) ...
    isstruct(x) && ...
    ~isempty(x));
addRequired(P,'hucIndex',@(x) ...
    isscalar(x) && ...
    ~isempty(x));
addRequired(P,'gridMask',@(x) ...
    isnumeric(x) && ...
    ismatrix(x) && ...
    ~isempty(x));
addRequired(P,'gridMaskGeoRasterRef',@(x) ...
    isa(x,'spatialref.GeoRasterReference'));

parse(P,nargin,nargout,topLevelRasterDir,topLevelVectorDir, ...
    rasterNanFloors,gridDensity,attributeFieldCell,hucCodeShapeStruct, ...
    hucIndex,gridMask,gridMaskGeoRasterRef);

%% Extract Vector Mosaic Data

disp('** Extracting Vector Mosaic Data **');

vectorMosaicData = extractVectorMosaicDataFnc( ...
    topLevelVectorDir, ...
    hucCodeShapeStruct, ...
    hucIndex, ...
    gridMaskGeoRasterRef );

%% Rasterize Vector Mosaic Data

disp('** Rasterizing Vector Mosaic Data **');

vector2RasterMosaicData = vector2RasterMosaicDataFnc( ...
    vectorMosaicData, ...
    attributeFieldCell, ...
    gridMask, ...
    gridMaskGeoRasterRef );

%% Extract Raster Mosaic Data

disp('** Extracting Raster Mosaic Data **');

rasterMosaicData = extractRasterMosaicDataFnc( ...
    topLevelRasterDir, ...
    rasterNanFloors, ...
    gridMask, ...
    gridMaskGeoRasterRef );

%% Generate Derived Data Products

disp('** Generating Derived Data Products **');

rasterNames = rasterMosaicData(:,2);
demMatch = strcmp(rasterNames,'digitalElevationModel');

if any(demMatch) == 0
    
    warning('No DEM Found & No DEM Derived Raster Datasets Generated');
    
else 
    
    demRasterData = rasterMosaicData{demMatch,1};
    gradientMosaicData = dem2GradientMosaicDataFnc( ...
    demRasterData, ...
    gridDensity, ...
    gridMask, ...
    gridMaskGeoRasterRef );

end

%% Concatenate to Final Output

disp('** Assembling Final Raster Mosaic Data Output **');

rawRasterMosaicData = vertcat( ...
    rasterMosaicData, ...
    gradientMosaicData, ...
    vector2RasterMosaicData );

end