function [ outputRasterMosaicData ] = reclassifyRasterMosaicDataFnc( ...
                                            inputRasterMosaicData, ...
                                            reclassifyCell, ...
                                            rasterNanFloorArray, ...
                                            categoricalDataFlagCell, ...
                                            breakCountCell, ...
                                            directionalityCell, ...
                                            gridMask, ...
                                            gridMaskGeoRasterRef )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

%% Parse Inputs

P = inputParser;

addRequired(P,'nargin',@(x) ...
    x == 5);
addRequired(P,'nargout',@(x) ...
    x == 1);
addRequired(P,'inputRasterMosaicData',@(x) ...
    isnumeric(x) && ...
    ismatrix(x) && ...
    ~isempty(x));
addRequired(P,'categoricalDataFlagCell',@(x) ...
    isscalar(x) && ...
    ~isempty(x));
addRequired(P,'reclassifyCell',@(x) ...
    cellfun(islogical(x));
addRequired(P,'breakCountCell',@(x) ...
    isscalar(x) && ...
    ~isempty(x));
addRequired(P,'directionalityCell',@(x) ...
    );
addRequired(P,'gridMask',@(x) ...
    isnumeric(x) && ...
    ismatrix(x) && ...
    ~isempty(x));
addRequired(P,'gridMaskGeoRasterRef',@(x) ...
    isa(x,'spatialref.GeoRasterReference'));

parse(P,nargin,nargout,inputRasterData,categoricalDataFlag,breakCount, ...
    gridMask,gridMaskGeoRasterRef);

%% Function Parameters


end
